[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "homeassistant==2024.3.3",
    "voluptuous==0.13.1",
]
