# Core Configuration
default_config: false

# HTTP Configuration
http:
  server_host: "0.0.0.0"
  server_port: !env_var PORT default=5000

# Only required components
frontend:

# Debug logging
logger:
  default: debug
  logs:
    custom_components.family_health_tracker: debug
    homeassistant.core: debug
    homeassistant.bootstrap: debug
    homeassistant.components.http: debug
    homeassistant.loader: debug

# Our integration
family_health_tracker:
  name: "Family Health"
  members: "John,Jane"